apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 2
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostPID: false
      hostIPC: false
      hostNetwork: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: http-echo
          image: hashicorp/http-echo
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 5678
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /
              port: 5678
              scheme: HTTP
          startupProbe:
            httpGet:
              path: /
              port: 5678
              scheme: HTTP
          env:
            - name: VERSION
              value: {{ .Chart.Version }}
            - name: PORT
              value: "5678"
      terminationGracePeriodSeconds: 80
